### ISSUE TITLE
`--release` flag must be the first flag when use `keygen upload`

### ISSUE THREAD

**Issue by hckhanh** [keygen-sh/keygen-cli#11]
This is the command that I used in GitHub Actions (macos-latest image):

```bash
keygen upload 'files.app.tar.gz' \
    --signature "$(cat 'files.app.tar.gz.sig')" \ 
    --release '1.1.10' \
    --package '***' \
    --filename 'files-silicon.app.tar.gz' \
    --platform 'macos' \
    --arch 'aarch64'
  shell: /bin/bash -e {0}
    KEYGEN_ACCOUNT_ID: ***
    KEYGEN_PRODUCT_ID: ***
    KEYGEN_PRODUCT_TOKEN: ***
```

Log:

```bash
error: required flag(s) "release" not set
Error: Process completed with exit code 1.
```

**Comment by hckhanh** [comment]
The problem is I pass the signature value incorrectly and I left the trailing space after `\` in the command, this is my mistake.
It should be:

```yml
      - name: Get update signature
        run: echo "UPDATE_SIGNATURE=$(cat 'files.app.tar.gz.sig')" >> "$GITHUB_ENV"
        working-directory: src-tauri/target/aarch64-apple-darwin/release/bundle/macos
      - name: Upload update file
        run: |
          keygen upload 'files.app.tar.gz' \
            --release '${{ github.event.release.tag_name }}' \
            --package '${{ secrets.KEYGEN_PACKAGE_ID }}' \
            --filename 'files.app.tar.gz' \
            --signature '${{ env.UPDATE_SIGNATURE }}' \ 
            --platform 'macos' \
            --arch 'aarch64'
        working-directory: src-tauri/target/aarch64-apple-darwin/release/bundle/macos
        env:
          KEYGEN_ACCOUNT_ID: ${{ secrets.KEYGEN_ACCOUNT_ID }}
          KEYGEN_PRODUCT_ID: ${{ secrets.KEYGEN_PRODUCT_ID }}
          KEYGEN_PRODUCT_TOKEN: ${{ secrets.KEYGEN_PRODUCT_TOKEN }}
```
