### ISSUE TITLE
GitHub action

### ISSUE THREAD

**Issue by morgante** [keygen-sh/keygen-cli#5]
It would be very helpful to have a GitHub action for interacting with keygen. In particular, to setup the CLI and issue new releases.

This can be scripted now, but requires some amount of toil.

**Comment by ezekg** [comment]
Thanks for the suggestion! What would the GitHub Action look like? I’m personally not too familiar with GitHub Actions to understand exactly what you’re looking for here, functionality-wise. Keygen is used for a lot of different applications, written in various languages, all with different build systems and requirements, so any official Action would need to support these.

**Comment by ezekg** [comment]
@morgante let me know if you have any thoughts here. 🙂

**Comment by morgante** [comment]
Agreed it shouldn't be specific to a language ecosystem. Other GitHub actions can take care of building the output, but this action would take care of taking built binaries and creating/uploading releases.

These are the steps I ended up implementing:
```
    - name: setup-keygen
      run: curl -sSL https://get.keygen.sh/keygen/latest/install.sh | sh
    - name: calculate version
      run: |
        version=$(cat ./apps/${{ matrix.app }}/package.json | jq -r .version)
        hash=($(md5sum ./${{ matrix.macos }}))
        timestamp=$(date '+%s')
        echo "release_tag=$hash" >> $GITHUB_ENV
        echo "version=$version-alpha.$timestamp" >> $GITHUB_ENV
    - name: create-release
      continue-on-error: true
      run: |
        keygen new --account 'custodian-dev' --tag '${{ env.release_tag }}' --product '${{ matrix.product }}' --token '${{ env.token }}' --channel 'alpha' --version ${{ env.version }}
        echo "HAS_RELEASE=TRUE" >> $GITHUB_ENV
    - name: upload-macos
      if: ${{ env.HAS_RELEASE }}
      run: keygen upload ./${{ matrix.macos }} --filename '${{ matrix.app }}-macos-${{ matrix.arch }}' --account 'custodian-dev' --product '${{ matrix.product }}' --token '${{ env.token }}' --release $version --platform macos --arch ${{ matrix.arch }}
    - name: upload-linux
      if: ${{ env.HAS_RELEASE }}
      run: keygen upload ./${{ matrix.linux }} --filename '${{ matrix.app }}-linux-${{ matrix.arch }}' --account 'custodian-dev' --product '${{ matrix.product }}' --token '${{ env.token }}' --release $version --platform linux --arch ${{ matrix.arch }}
```

I'd love to condense this into something like this:
```
    -name: Build and push
      uses: keygen-sh/keygen-release-action@v1
      with:
        product: ${{ matrix.product }}
        release: ${{ env.version }}
        tag: ${{ env.release_tag }}
        attachTimestampSuffix: true
        token: ${{ env.token }}
        account: custodian-dev
        files:
          - path: ./${{ matrix.macos }}
            platform: macos
            arch: ${{ matrix.arch }}
          - path: ./${{ matrix.linux }}
            platform: linux
            arch: ${{ matrix.arch }}
````
